accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
    login, logout, password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete,
)

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^profile/index/$', views.index, name='index'),
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),

    url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

    url(r'^profile/sensor/$', views.sensor_measures,  name='sensor_measures')

]

tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from tutorial import views


urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)


    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

class sensor_state(models.Model):
    name = models.CharField(max_length=50, default='', unique=True)


class sensor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,  related_name='sensor' )
    name = models.CharField(max_length=200, default='')
    seriennummer = models.FloatField(max_length=100, default='', unique=True)
    state = models.ForeignKey(sensor_state)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

class sensormeasure(models.Model):
    sensor = models.ForeignKey(sensor, related_name="sensormeasurefeld")
    co2 = models.FloatField(max_length=20)
    temperature = models.FloatField(max_length=20)
    humidity = models.FloatField(max_length=20)
    vlufttemperature = models.FloatField(max_length=20)
    abgastemp = models.FloatField(max_length=20)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    template_name='/something/else'

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

        class Meta:
            model = UserProfile
            fields = (
                'city'
            )

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
import pprint

from accounts.forms import (
    RegistrationForm,
    EditProfileForm
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import sensormeasure
from .models import UserProfile
from .models import sensor, sensor_state

def index(request):
    return render(request, 'index.html')

def home(request):
    numbers = [1,2,3,4,5]
    name = 'Fabian Stadler'
    user = request.user

    args = {'myName': name, 'numbers': numbers, 'user':user}
    return render(request, 'accounts/home.html', args)

def register(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:home'))
    else:
        form = RegistrationForm()

        args = {'form': form}
        return render(request, 'accounts/reg_form.html', args)

def view_profile(request):
    user = request.user
    sensors = sensor.objects.filter(user=request.user.id)
    args = {'user': user, 'sensors': sensors}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

def sensor_measures(request):
    user = request.user
    sensors = sensor.objects.filter(user=request.user.id)
    sensormeasures = sensormeasure.objects.all()
    args = {'user': user,'sensors': sensors, 'sensormeasures': sensormeasures }#'sensormeasures':sensormeasures
    return render(request, 'accounts/sensor_measure.html', args)

tutorial/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

accounts/templates/accounts/change_password.html
{% extends 'accounts/../base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'accounts/../base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

accounts/templates/accounts/home.html
{% extends 'accounts/../base.html' %}

<h1>Home</h1>
{% block head %}
<title>Home</title>


{% endblock %}


{% block body %}
    <div class="container">
<h1>Hallo {{ user.first_name }}</h1>
    <h3>Dein Sensor läuft wie gewohnt im Umkreis von {{ user.userprofile.city }}</h3>

    <canvas id="myChart1"></canvas>
<script>
        $(function () {
            var data = {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(220,220,220,0.2)",
                    strokeColor: "rgba(220,220,220,1)",
                    pointColor: "rgba(220,220,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: [65, 59, 80, 81, 56, 55, 40]
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(151,187,205,0.2)",
                    strokeColor: "rgba(151,187,205,1)",
                    pointColor: "rgba(151,187,205,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: [28, 48, 40, 19, 86, 27, 90]
                }
                ]
            };

            var option = {
            responsive: true,
            };

            // Get the context of the canvas element we want to select
            var ctx = document.getElementById("myChart1").getContext('2d');
            var myLineChart = new Chart(ctx).Line(data, option); //'Line' defines type of the chart.
        });
    </script>


</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/../pages-login-omega.html' %}

{% block body %}
<div class="landingpage">


<div class="container">
    <h1>Welcome</h1>
    <p>
        You can log in here!
    </p>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/../base.html' %}

{% block body %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/../base.html' %}


{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
    <div class="container">
    <div class="row">
  <div class="col-md-8"> <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>

    <h1>Sensoren</h1>
    {% for sensor in sensors %}

        <a href="{% url 'accounts:sensor_measures' %}">{{ sensor.name }}</a>

    {% endfor %}
  </div>

  <div class="col-md-4">

    </div>
  </div>
</div>








{% endblock %}

{% block body-diagramme %}
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'accounts/../base.html' %}

{% block body %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'accounts/../base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset</h1>
    <p>
        Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'accounts/../base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset complete</h1>
    <a href="{% url 'accounts:login' %}">Log in</a>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'accounts/../base.html' %}

{% block body %}
<div class="container">
    <h1>Enter new password</h1>
    <p>

    </p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'accounts/../base.html' %}

{% block body %}
<div class="container">
    <h1>Password reset sent</h1>
    <p>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
</div>
{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/sensor_measure.html
{% extends 'accounts/../index.html' %}


<title>Profil</title>






{% block body %}
<div class="container">
<div class="row">
  <div class="col-md-4">


   <div class="sensormeasures_body">
   <h1>Mein Profil</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    <p>City: {{ user.userprofile.city }}</p>

    {% for sensor in sensors %}
     <h2> Sensorinfos </h2>
     <p>Modell: {{ sensor.name }}</p>
     <p>Seriennummer: {{ sensor.seriennummer }}</p>
     <p>Installiert: {{ sensor.created }}</p>
      <p>Installiert: {{ sensor.created }}</p>
        <h2>Meine Werte</h2>

       {% for  sensormeasure in sensormeasures  %}
           {% if sensormeasure.sensor_id == sensor.id %}
            <p>Co2: {{sensormeasure.co2  }}</p>
            <p>Abgastemperatur: {{ sensormeasure.co2 }}</p>
            <p>Verbrennungslufttemperatur: {{ sensormeasure.co2 }}</p>
            <p>Feuchtigkeit: {{ sensormeasure.co2 }}</p>
           {% endif %}
       {% endfor %}
{% endfor %}

<!--Diagramme --->




    </div>

  </div>
  <div class="col-md-8">

  <canvas id="myChart"></canvas>
    <script>
        $(function () {
    var data = {
    labels: ["Co2", "Abgastemperatur", "Verbrennungsluttemperatur", "O2", "CO", "Effizienz", "Umweltbelastung"],
    datasets: [
        {
            label: "My First dataset",
            fillColor: "rgba(220,220,220,0.2)",
            strokeColor: "rgba(220,220,220,1)",
            pointColor: "rgba(220,220,220,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(220,220,220,1)",
            data: [65, 59, 90, 81, 56, 55, 40]
        },
        {
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: [28, 48, 40, 19, 96, 27, 100]
        }
    ]
};
    var option = {
    responsive: true,
    };

    // Get the context of the canvas element we want to select
    var ctx = document.getElementById("myChart").getContext('2d');
   var myRadarChart = new Chart(ctx).Radar(data, option);
});
    </script>



    </div>

</div>









{% endblock %}



    </div>

accounts/templates/base.html
<html>


     <!-- Head AdminTemp Anfang -->
        <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

    <!-- Bootstrap -->
    <link href="../static/accounts/admintemp/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="../static/accounts/admintemp/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="../static/accounts/admintemp/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="../static/accounts/admintemp/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="../static/accounts/admintemp/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="../static/accounts/admintemp/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="../static/accounts/admintemp/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="../static/accounts/admintemp/css/custom.min.css" rel="stylesheet">
  </head>

    <!-- Head AdminTemp Ende -->
    {% load static %}

    <!--Bootstrap -->

    <link href="{% static 'accounts/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'accounts/bootstrap/css/bootstrap.css.map' %}" rel="stylesheet">
    <link href="{% static 'accounts/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'accounts/bootstrap/css/bootstrap.min.css.map' %}" rel="stylesheet">
    <link href="{% static 'accounts/bootstrap/css/bootstrap-theme.css' %}" rel="stylesheet">
     <link href="{% static 'accounts/bootstrap/css/bootstrap-theme.css.map' %}" rel="stylesheet">
     <link href="{% static 'accounts/bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">
     <link href="{% static 'accounts/bootstrap/css/bootstrap-theme.min.css.map' %}" rel="stylesheet">

     <script type="text/javascript" src="{% static 'accounts/bootstrap/js/bootstrap.js'%}"></script>
     <script type="text/javascript" src="{% static 'accounts/bootstrap/js/bootstrap.min.js'%}"></script>
     <script type="text/javascript" src="{% static 'accounts/bootstrap/js/npm.js'%}"></script>

<!-- Chart Css & JS -->

     <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'accounts/mdbcharts/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Material Design Bootstrap -->
    <link href="{% static 'accounts/mdbcharts/css/mdb.min.css'%}" rel="stylesheet">

    <!-- Your custom styles (optional) -->
    <link href="{% static 'accounts/mdbcharts/css/style.css' %}" rel="stylesheet">

<!-- SCRIPTS -->

    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'accounts/mdbcharts/js/jquery-3.1.1.min.js'%}"></script>

    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'accounts/mdbcharts/js/tether.min.js'%}"></script>

    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'accounts/mdbcharts/js/bootstrap.min.js'%}"></script>

    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'accounts/mdbcharts/js/mdb.min.js'%}"></script>

        <!-- Ende Mdb Charts -->

        <!-- Mein Css -->

        <link rel="stylesheet" href="{% static 'accounts/style.css' %}">

        {% block head %}
        <title>Base</title>

        {% endblock %}
    </head>
<!-- Alte Navigation Anfang -->

     <body>
        <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Smart Chimney System</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:home' %}">Home</a></li>
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                     <li><a href="{% url 'accounts:sensor_measures' %}">Sensoren</a></li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif %}
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
<!-- Alte Navigation Ende -->

        {% block body %}
            <h1>Base</h1>

        {% endblock %}




    </body>






</html>